version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pip install sphinx-autoapi

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
