[metadata]
name = logitorch
version = 0.0.1a2
author = Chadi Helwe
author_email = chadi.helwe@gmail.com
url = https://github.com/ChadiHelwe/logitorch
license = Apache License 2.0
description = LogiTorch is a pytorch-based library for logical reasoning in natural language
long_description_content_type = text/markdown
long_description = file: README.md
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
zip_safe = False
include_package_data = True
packages = find:
package_dir =
    =src
install_requires =
    torch~=2.8.0
    lightning~=2.5.0
    transformers~=4.57.0
    requests~=2.32.0
    tqdm~=4.66.0
    textblob~=0.18.0
    nltk~=3.9.0
    protobuf~=6.32.0
    datasets~=4.1.0
    evaluate~=0.4.6

[options.extras_require]
dev =
    tox~=4.23.0
    isort~=5.13.0
    mypy~=1.13.0
    black~=24.10.0
    pytest~=8.3.0
    flake8~=7.1.0
    pre-commit~=4.0.0
    types-requests~=2.32.0
    sphinx~=8.1.0
    sphinx-autoapi~=3.4.0
    astroid<4.0  # Required by sphinx-autoapi 3.4.0
    furo~=2024.8.0

[options.packages.find]
where = src
exclude = test*

[flake8]
max-line-length = 88
exclude =
    .git,
    __pycache__,
    docs/source/conf.py,
    old,
    env,
    build,
    dist
extend-ignore =
    E203
    E501
