EXCPLICIT_CONNECTIVES = {
    "once",
    "although",
    "though",
    "but",
    "because",
    "nevertheless",
    "before",
    "for example",
    "until",
    "if",
    "previously",
    "when",
    "and",
    "so",
    "then",
    "while",
    "as long as",
    "however",
    "also",
    "after",
    "separately",
    "still",
    "so that",
    "or",
    "moreover",
    "in addition",
    "instead",
    "on the other hand",
    "as",
    "for instance",
    "nonetheless",
    "unless",
    "meanwhile",
    "yet",
    "since",
    "rather",
    "in fact",
    "indeed",
    "later",
    "ultimately",
    "as a result",
    "either or",
    "therefore",
    "in turn",
    "thus",
    "in particular",
    "further",
    "afterward",
    "next",
    "similarly",
    "besides",
    "if and when",
    "nor",
    "alternatively",
    "whereas",
    "overall",
    "by comparison",
    "till",
    "in contrast",
    "finally",
    "otherwise",
    "as if",
    "thereby",
    "now that",
    "before and after",
    "additionally",
    "meantime",
    "by contrast",
    "if then",
    "likewise",
    "in the end",
    "regardless",
    "thereafter",
    "earlier",
    "in other words",
    "as soon as",
    "except",
    "in short",
    "neither nor",
    "furthermore",
    "lest",
    "as though",
    "specifically",
    "conversely",
    "consequently",
    "as well",
    "much as",
    "plus",
    "and",
    "hence",
    "by then",
    "accordingly",
    "on the contrary",
    "simultaneously",
    "for",
    "in sum",
    "when and if",
    "insofar as",
    "else",
    "as an alternative",
    "on the one hand on the other hand",
}

PUNCTUATION_DELIMETERS = {".", ",", ";", ":"}


class DiscourseDelimiter:
    pass
